### ISSUE TITLE
expo start --web is not working

### ISSUE THREAD

**Issue by abdulbarik** [critesjosh/celo-dappkit#7]
Hi @critesjosh 
Thank You for sharing this super example to work with celo.
 I followed the `README.md` file to up the app. I am able to test by tunnel and mobile app, but when I try to use as web app and open `http://localhost:19006` it redirects to `http://localhost:19006/[object%20Object]` and start auto refreshing.

Can you please help me resolve this?

**Comment by critesjosh** [comment]
Excellent call out. Can you try this repo for building a web based dapp using dappkit instead? https://github.com/celo-org/dappkit-web-starter

Let me know how it goes. If it works for you, I will update the README.md to include it.

**Comment by abdulbarik** [comment]
Thanks @critesjosh  for prompt response, I'll check and get back to you.

**Comment by abdulbarik** [comment]
Thanks, @critesjosh,
 I think the answer of this issue is [ https://github.com/celo-org/dappkit-web-starter]( https://github.com/celo-org/dappkit-web-starter) 

So closing this issue.
